version: '2'

services:

  flask-api:
    build: .
    image: flask-api:latest
    env_file: docker-compose.env
    ports:
      - 5000:5000
    depends_on: 
      - mongo-db

  mongo-db:
    image: mongo
    container_name: local-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
